// auth
export const AUTH_BEGIN = 'AUTH_BEGIN'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_SSO_ERROR = 'AUTH_SSO_ERROR'
export const SET_DISCOURSE_SSO = '@@AUTH/SET_DISCOURSE_SSO'

// Register
export const REGISTER_BEGIN = 'REGISTER_BEGIN'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// Forgot Password
export const FORGOT_PASSWORD_BEGIN = 'FORGOT_PASSWORD_BEGIN'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR'

// Send Password
export const SEND_PASSWORD_BEGIN = 'SEND_PASSWORD_BEGIN'
export const SEND_PASSWORD_SUCCESS = 'SEND_PASSWORD_SUCCESS'
export const SEND_PASSWORD_ERROR = 'SEND_PASSWORD_ERROR'

// Change Password
export const CHANGE_PASSWORD_BEGIN = '@@AUTH/CHANGE_PASSWORD_BEGIN'
export const CHANGE_PASSWORD_SUCCESS = '@@AUTH/CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_ERROR = '@@AUTH/CHANGE_PASSWORD_ERROR'

// get summary
export const GET_FILLING_BEGIN = 'GET_FILLING_BEGIN'
export const GET_FILLING_SUCCESS = 'GET_FILLING_SUCCESS'
export const GET_FILLING_ERROR = 'GET_FILLING_ERROR'
export const GET_SUMMARY_SURA = 'GET_SUMMARY_SURA'
export const GET_ERROR_SUMMARY_SURA_ERROR = 'GET_ERROR_SUMMARY_SURA_ERROR'
export const GET_ANSWERS_INSTACE = 'GET_ANSWERS_INSTACE'
export const GET_ANSWERS_INSTANCE_SUCCESS = 'GET_ANSWERS_INSTANCE_SUCCESS'
export const GET_ANSWERS_INSTANCE_ERROR = 'GET_ANSWERS_INSTANCE_ERROR'
export const GET_USER_CERTIFICATES_SUCCESS = 'GET_USER_CERTIFICATES_SUCCESS'
export const GET_USER_CERTIFICATES_ERROR = 'GET_USER_CERTIFICATES_ERROR'
export const COMPLETE_SURA = 'COMPLETE_SURA'

// Upload
export const UPLOAD_FILE = 'UPLOAD_FILE'
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR'

// Answer
export const POST_ANSWER_BEGIN = 'POST_ANSWER_BEGIN'
export const POST_ANSWER_SUCCESS = 'POST_ANSWER_SUCCESS'
export const POST_ANSWER_ERROR = 'POST_ANSWER_ERROR'

export const GET_ANSWER_BEGIN = 'GET_ANSWER_BEGIN'
export const GET_ANSWER_SUCCESS = 'GET_ANSWER_SUCCESS'
export const GET_ANSWER_ERROR = 'GET_ANSWER_ERROR'

export const HAS_MIGRATED_ANSWERS = '@@ONBOARDING/HAS-MIGRATED-ANSWERS'

// get accountant-customers
export const GET_CUSTOMERS_BEGIN = 'GET_CUSTOMERS_BEGIN'
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS'
export const ACTUAL_PERSON = 'ACTUAL_PERSON'
export const GET_CUSTOMERS_ERROR = 'GET_CUSTOMERS_ERROR'
export const GET_PROFESIONAL_CARD_BEGIN = 'GET_PROFESIONAL_CARD_BEGIN'
export const GET_PROFESIONAL_CARD_SUCCESS = 'GET_PROFESIONAL_CARD_SUCCESS'
export const GET_PROFESIONAL_CARD_ERROR = 'GET_PROFESIONAL_CARD_ERROR'
export const UPLOAD_PROFESIONAL_CARD_BEGIN = 'UPLOAD_PROFESIONAL_CARD_BEGIN'
export const UPLOAD_PROFESIONAL_CARD_SUCCESS = 'UPLOAD_PROFESIONAL_CARD_SUCCESS'
export const UPLOAD_PROFESIONAL_CARD_ERROR = 'UPLOAD_PROFESIONAL_CARD_ERROR'

// Onboarding
export const GET_QUESTIONS_BY_CODE_CLEAR = 'GET_QUESTIONS_BY_CODE_CLEAR'
export const GET_QUESTIONS_BY_CODE_ERROR = 'GET_QUESTIONS_BY_CODE_ERROR'
export const GET_QUESTIONS_BY_CODE = 'GET_QUESTIONS_BY_CODE'
export const GET_GROUP_BEGIN = 'GET_GROUP_BEGIN'
export const GET_GROUP = 'GET_GROUP'
export const UPDATE_GROUP_INSTANCE_SUCCESS =
  '@@ONBOARDING/UPDATE_GROUP/INSTANCE_SUCCESS'
export const ERROR_GROUP = 'ERROR_GROUP'
export const GET_GROUP_QUESTIONS = 'GET_GROUP_QUESTIONS'
export const GET_ONBOARDING_QUESTION = 'GET_ONBOARDING_QUESTION'
export const DELETE_INSTANCE = 'DELETE_INSTANCE'
export const ERROR_DELETE_INSTANCE = 'ERROR_DELETE_INSTANCE'
export const GO_TO_ONBOARDING = 'GO_TO_ONBOARDING'
export const ANSWER_ONBOARDING = 'ANSWER_ONBOARDING'
export const ERROR_ANSWER_ONBOARDING = 'ERROR_ANSWER_ONBOARDING'
export const GET_ANSWER_BY_CODE = 'GET_ANSWER_BY_CODE'
export const GET_ANSWER_BY_CODE_ERROR = 'GET_ANSWER_BY_CODE_ERROR'
export const GET_ANSWER_ONBOARDING = 'GET_ANSWER_ONBOARDING'
export const POST_ONBOARDING_ANSWER_BEGIN = 'POST_ONBOARDING_ANSWER_BEGIN'
export const POST_ONBOARDING_ANSWER_ERROR = 'POST_ONBOARDING_ANSWER_ERROR'
export const POST_ONBOARDING_ANSWER_SUCCESS = 'POST_ONBOARDING_ANSWER_SUCCESS'
export const NEW_DIAN_CREDENTIALS = 'NEW_DIAN_CREDENTIALS'
export const NEW_DIAN_CREDENTIALS_BEGIN = 'NEW_DIAN_CREDENTIALS_BEGIN'
export const POST_DIAN_CREDENTIALS_BEGIN = 'POST_DIAN_CREDENTIALS_BEGIN'
export const POST_DIAN_CREDENTIALS_ERROR = 'POST_DIAN_CREDENTIALS_ERROR'
export const POST_DIAN_CREDENTIALS_SUCCESS = 'POST_DIAN_CREDENTIALS_SUCCESS'
export const DELETE_INSTANCE_ONBORDING = 'DELETE_INSTANCE_ONBORDING'
export const CLEAR_DATA_ONBORDING = 'CLEAR_DATA_ONBORDING'
export const REMOVE_CERTIFICATES = 'REMOVE_CERTIFICATES'
export const REMOVE_CERTIFICATES_ERROR = 'REMOVE_CERTIFICATES_ERROR'
export const DELETE_INSTANCE_QUESTIONS_OB = 'DELETE_INSTANCE_QUESTIONS_OB'
export const DELETE_INSTANCE_QUESTIONS_OB_BEGIN =
  'DELETE_INSTANCE_QUESTIONS_OB_BEGIN'
export const UPDATE_DIAN_DOCUMENT_PROGRESS = 'UPDATE_DIAN_DOCUMENT_PROGRESS'
export const UPDATE_DIAN_DOCUMENT_FILES = 'UPDATE_DIAN_DOCUMENT_FILES'
export const FINISH_DIAN_DOCUMENT_PROGRESS = 'FINISH_DIAN_DOCUMENT_PROGRESS'
export const CLEAN_UP_DIAN_LOADING = 'CLEAN_UP_DIAN_LOADING'
export const CANCEL_FILE_UPLOAD_SUCCESS =
  '@@ONBOARDING/CANCEL_FILE_UPLOAD_SUCCESS'
export const CANCEL_FILE_UPLOAD_ERROR = '@@ONBOARDING/CANCEL_FILE_UPLOAD_ERROR'
export const CANCEL_FILE_UPLOAD_BEGIN = '@@ONBOARDING/CANCEL_FILE_UPLOAD_BEGIN'
export const ONBOARDING_GET_CONFIG_BEGIN = '@@ONBOARDING/GET_CONFIG/BEGIN'
export const ONBOARDING_GET_CONFIG_SUCCESS = '@@ONBOARDING/GET_CONFIG/SUCCESS'
export const ONBOARDING_GET_CONFIG_ERROR = '@@ONBOARDING/GET_CONFIG/ERROR'
export const ONBOARDING_CLEAN_CONFIG = '@@ONBOARDING/GET_CONFIG/CLEAN'
export const ENABLE_MODAL_PRELOAD_INFO_SUCCESS =
  'ENABLE_MODAL_PRELOAD_INFO_SUCCESS'
export const ENABLE_MODAL_PRELOAD_INFO_ERROR = 'ENABLE_MODAL_PRELOAD_INFO_ERROR'
export const MIGRATION_SUCCESS = 'MIGRATION_SUCCESS'
export const MIGRATION_ERROR = 'MIGRATION_ERROR'
export const NOT_MIGRATE_SUCCESS = 'NOT_MIGRATE_SUCCESS'
export const NOT_MIGRATE_ERROR = 'NOT_MIGRATE_ERROR'
export const CLEAR_MIGRATE_FLAGS = 'CLEAR_MIGRATE_FLAGS'
export const CLEAR_MIGRATION_ERROR_FLAG = 'CLEAR_MIGRATION_ERROR_FLAG'
export const DISCARD_MIGRATE_SUCCESS = 'DISCARD_MIGRATE_SUCCESS'
export const DISCARD_MIGRATE_ERROR = 'DISCARD_MIGRATE_SUCCESS'

// Summary
export const GET_SUMMARY_BEGIN = 'GET_SUMMARY_BEGIN'
export const GETT_SUMMARY = 'GETT_SUMMARY'
export const ERROR_UPDATE_FILLING_STATUS = 'ERROR_UPDATE_FILLING_STATUS'

export const GETT_ERROR_SUMMARY = 'GETT_ERROR_SUMMARY'
export const GET_QUESTION_BEGIN = 'GET_QUESTION_BEGIN'
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS'
export const GET_QUESTION_ERROR = 'GET_QUESTION_ERROR'

export const CLEAR_SUMMARY_DATA = 'CLEAR_SUMMARY_DATA'

export const GET_PLAN_BEGIN = 'GET_PLAN_BEGIN'
export const GET_PLAN_SUCCESS = 'GET_PLAN_SUCCESS'
export const GET_PLAN_ERROR = 'GET_PLAN_ERROR'

export const GET_COUNTRY_BEGIN = 'GET_COUNTRY_BEGIN'
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS'
export const GET_COUNTRY_ERROR = 'GET_COUNTRY_ERROR'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

// create a new filling
export const CREATE_FILLING_BEGIN = 'GET_FILLING_BEGIN'
export const CREATE_FILLING_SUCCESS = 'CREATE_FILLING_SUCCESS'
export const CREATE_FILLING_ERROR = 'GET_FILLING_ERROR'

export const DELETE_FILING = 'DELETE_FILING'

// create a new filling --> I should declare
export const CREATE_FILLING_DECLARE_BEGIN = 'CREATE_FILLING_DECLARE_BEGIN'
export const CREATE_FILLING_DECLARE_SUCCESS = 'CREATE_FILLING_DECLARE_SUCCESS'
export const CREATE_FILLING_DECLARE_ERROR = 'CREATE_FILLING_DECLARE_ERROR'
export const UPDATE_PAID_EXTERNALLY_STATUS = 'UPDATE_PAID_EXTERNALLY_STATUS'
export const UPDATE_PAID_EXTERNALLY_STATUS_ERROR =
  'UPDATE_PAID_EXTERNALLY_STATUS_ERROR'

// management people
export const GET_PERSON_SUCCESS = 'GET_PERSON_SUCCESS'
export const CREATE_PERSON_SUCCESS = 'CREATE_PERSON_SUCCESS'
export const EDIT_PERSON_SUCCESS = 'EDIT_PERSON_SUCCESS'
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS'
export const DELETE_PERSON_ERROR = 'DELETE_PERSON_ERROR'
export const GET_PERSON_FILING_SUCCESS = 'GET_PERSON_FILING_SUCCESS'
export const CREATE_PERSON_FILLING_SUCCESS = 'GET_PERSON_FILING_SUCCESS'

// get dashboard Groups
export const GET_GROUPS_BEGIN = 'GET_GROUPS_BEGIN'
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS'
export const GET_GROUPS_ERROR = 'GET_GROUPS_ERROR'
export const SET_HELP_INFO = 'SET_HELP_INFO'
export const CLEAR_HELP_INFO = 'CLEAR_HELP_INFO'
export const GIVE_FEEDBACK = 'GIVE_FEEDBACK'
export const SELECT_CERTIFICATE = 'SELECT_CERTIFICATE'
export const DELETE_INSTANCE_DASHBOARD = 'DELETE_INSTANCE_DASHBOARD'
export const ERROR_DELETE_INSTANCE_DASHBOARD = 'ERROR_DELETE_INSTANCE_DASHBOARD'

// Payment
export const PAYMENT_ORDER = 'PAYMENT_ORDER'
export const PAYMENT_ORDER_ERROR = 'PAYMENT_ORDER_ERROR'
export const PAYMENT_ORDER_CANCELED = 'PAYMENT_ORDER_CANCELED'
export const STATUS_PAYMENT = 'STATUS_PAYMENT'
export const STATUS_PAYMENT_ERROR = 'STATUS_PAYMENT_ERROR'
export const FILLING_STATE = 'FILLING_STATE'
export const FILLING_STATE_ERROR = 'FILLING_STATE_ERROR'
export const PAYMENT_ORDER_INFO = '@@payment/payment-order-info'
export const SEND_DECLARATION_FROM_ACCOUNTANT_SUCCESS =
  'SEND_DECLARATION_FROM_ACCOUNTANT_SUCCESS'
export const SEND_DECLARATION_FROM_ACCOUNTANT_ERROR =
  'SEND_DECLARATION_FROM_ACCOUNTANT_ERROR'
export const ONBOARDING_CLEAR_MESSAGE_TO_SHOW =
  'ONBOARDING_CLEAR_MESSAGE_TO_SHOW'
export const GET_BANK_LIST_SUCESS = 'GET_BANK_LIST_SUCESS'
export const GET_PATMENT_REQUEST_ERROR = 'GET_PATMENT_REQUEST_ERROR'
export const GET_TAX_FILE_PAYMENT_SUCCESS = 'GET_TAX_FILE_PAYMENT_SUCCESS'
export const CLEAR_TAX_FILE_PAYMENT = 'CLEAR_TAX_FILE_PAYMENT'
export const HIDDEN_PAYMENT_MODAL_SUCESS = 'HIDDEN_PAYMENT_MODAL_SUCESS'
export const CLEAR_PAYMENT_MESSAGE_ERROR_SUCCESS =
  'CLEAR_PAYMENT_MESSAGE_ERROR_SUCCESS'
export const GET_EVENT_CALENDLY_SUCCESS = 'GET_EVENT_CALENDLY_SUCCESS'
export const GET_EVENT_CALENDLY_ERROR = 'GET_EVENT_CALENDLY_ERROR'
export const CANCEL_EVENT_CALENDLY_ERROR = 'CANCEL_EVENT_CALENDLY_ERROR'
export const SET_COUPON_FIRST_PURCHASE = 'SET_COUPON_FIRST_PURCHASE'

// Tax Engine
export const COMPUTED_TAXES = 'COMPUTED_TAXES'
export const COMPUTED_TAXES_ERROR = 'COMPUTED_TAXES_ERROR'
export const STATUS_TAX_ENGINE = 'STATUS_TAX_ENGINE'
export const STATUS_TAX_ENGINE_ERROR = 'STATUS_TAX_ENGINE_ERROR'
export const CLEAR_ENGINE_STATUS = 'CLEAR_ENGINE_STATUS'

export const SEARCH_USER_BY_FILLING_ERROR = 'SEARCH_USER_BY_FILLING_ERROR'
export const SEARCH_USER_BY_FILLING_SUCCESS = 'SEARCH_USER_BY_FILLING_SUCCESS'
export const SEARCH_USER_BY_FILLING_BEGIN = 'SEARCH_USER_BY_FILLING_BEGIN'
export const SEARCH_USER_BY_FILLING_0_RESULTS =
  'SEARCH_USER_BY_FILLING_0_RESULTS'

export const CHANGE_FILING_ACTIVE_STATUS_BEGIN =
  'CHANGE_FILING_ACTIVE_STATUS_BEGIN'
export const CHANGE_FILING_ACTIVE_STATUS_ERROR =
  'CHANGE_FILING_ACTIVE_STATUS_ERROR'
export const CHANGE_FILING_ACTIVE_STATUS_SUCCESS =
  'CHANGE_FILING_ACTIVE_STATUS_SUCCESS'

// Declarations documents
export const DOCUMENTS_LOADING = '@@payment/documents-loading'
export const DOCUMENTS_SUCCESS = '@@payment/documents-success'
export const DOCUMENTS_ERROR = '@@payment/documents-error'
export const DECLARATION_SYNC = '@@payment/declaration-sync'
export const GET_LITHOGRAPHIC_BEGIN = 'GET_LITHOGRAPHIC_BEGIN'
export const GET_LITHOGRAPHIC_SUCCESS = 'GET_LITHOGRAPHIC_SUCCESS'
export const GET_LITHOGRAPHIC_ERROR = 'GET_LITHOGRAPHIC_ERROR'
export const SET_DOCUMENTS_LOADING_SUCCESS = 'SET_DOCUMENTS_LOADING_SUCCESS'

export const IS_FILLED_COMPLETE = 'IS_FILLED_COMPLETE'
export const CLEAR_LOCAL_OBJECTS = 'CLEAR_LOCAL_OBJECTS'
export const CLEAR_STATUS_TAX_ENGINE = 'CLEAR_STATUS_TAX_ENGINE'
export const CLEAR_COMPUTE_TAXES = 'CLEAR_COMPUTE_TAXES'

// Coupons
export const REDEEM_COUPON_BEGIN = 'REDEEM_COUPON_BEGIN'
export const REDEEM_COUPON = 'REDEEM_COUPON'
export const REDEEM_COUPON_ERROR = 'REDEEM_COUPON_ERROR'

// Referral list
export const GET_REFERRED_USERS = 'GET_REFERRED_USERS'

// tax recover
export const TAX_RECEIVE_INFO_BEGIN = 'TAX_RECEIVE_INFO_BEGIN'
export const TAX_RECEIVE_INFO_SUCCESS = 'TAX_RECEIVE_INFO_SUCCESS'
export const TAX_RECEIVE_INFO_ERROR = 'TAX_RECEIVE_INFO_ERROR'

export const TAX_REDEEM_COUPON = 'TAX_REDEEM_COUPON'
export const TAX_REDEEM_COUPON_ERROR = 'TAX_REDEEM_COUPON_ERROR'

export const TAX_STATUS_PAYMENT_INFO_SUCCESS = 'TAX_STATUS_PAYMENT_INFO_SUCCESS'
export const TAX_STATUS_PAYMENT_INFO_ERROR = 'TAX_STATUS_PAYMENT_INFO_ERROR'

export const TAX_ORDER_PAYMENT_SUCCESS = 'TAX_ORDER_PAYMENT_SUCCESS'
export const TAX_ORDER_PAYMENT_ERROR = 'TAX_ORDER_PAYMENT_ERROR'

// Plans
export const PLANS_LOAD = '@@payment/plans-load'
export const PLANS = '@@payment/plans'
export const PLANS_ERROR = '@@payment/plans-error'
export const COUPON_VERIFY_LOAD = '@@payment/coupon-verify-load'
export const COUPON_VERIFY = '@@payment/coupon-verify'
export const COUPON_VERIFY_ERROR = '@@payment/coupon-verify-error'
export const COUPON_CLEAR = '@@payment/coupon-clear'

export const LOADING_NIT_RUT_UPDATE = 'LOADING_NIT_RUT_UPDATE'
export const SET_QUESTIONS_AND_ANSWERS = 'SET_QUESTIONS_AND_ANSWERS'
export const CLEAR_QUESTIONS_AND_ANSWERS = 'CLEAR_QUESTIONS_AND_ANSWERS'
export const QUESTIONS_AND_ANSWERS_SAVED = 'QUESTIONS_AND_ANSWERS_SAVED'

// Assistant screen v2
export const SEARCH_ASSISTANT_USERS_SUCCESS = 'SEARCH_ASSISTANT_USERS_SUCCESS'
export const SEARCH_ASSISTANT_USERS_ERROR = 'SEARCH_ASSISTANT_USERS_ERROR'
export const SEARCH_ASSISTANT_PERSONS_SUCCESS =
  'SEARCH_ASSISTANT_PERSONS_SUCCESS'
export const SEARCH_ASSISTANT_PERSONS_ERROR = 'SEARCH_ASSISTANT_PERSONS_ERROR'
export const SEARCH_ASSISTANT_FILINGS_BY_PERSON_SUCCESS =
  'SEARCH_ASSISTANT_FILINGS_BY_PERSON_SUCCESS'
export const SEARCH_ASSISTANT_FILINGS_BY_PERSON_ERROR =
  'SEARCH_ASSISTANT_FILINGS_BY_PERSON_ERROR'
export const SEARCH_ASSISTANT_DOCUMENTS_BY_FILING_SUCCESS =
  'SEARCH_ASSISTANT_DOCUMENTS_BY_FILING_SUCCESS'
export const SEARCH_ASSISTANT_DOCUMENTS_BY_FILING_ERROR =
  'SEARCH_ASSISTANT_DOCUMENTS_BY_FILING_ERROR'
export const SEARCH_ASSISTANT_ENGINES_BY_FILING_SUCCESS =
  'SEARCH_ASSISTANT_ENGINES_BY_FILING_SUCCESS'
export const SEARCH_ASSISTANT_ENGINES_BY_FILING_ERROR =
  'SEARCH_ASSISTANT_ENGINES_BY_FILING_SUCCESS'
export const SEARCH_ASSISTANT_PAYMENTS_BY_FILING_SUCCESS =
  'SEARCH_ASSISTANT_PAYMENTS_BY_FILING'
export const SEARCH_ASSISTANT_PAYMENTS_BY_FILING_ERROR =
  'SEARCH_ASSISTANT_PAYMENTS_BY_FILING_ERROR'
export const SAVE_ASSISTANT_USER_SUCCESS = 'SAVE_ASSISTANT_USER_SUCCESS'
export const SAVE_ASSISTANT_USER_ERROR = 'SAVE_ASSISTANT_USER_ERROR'
export const SAVE_ASSISTANT_PERSON_SUCCESS = 'SAVE_ASSISTANT_PERSON_SUCCESS'
export const SAVE_ASSISTANT_PERSON_ERROR = 'SAVE_ASSISTANT_PERSON_ERROR'
export const CLEAR_ALL_ASSISTANT_DATA = 'CLEAR_ALL_ASSISTANT_DATA'
export const UPDATE_ASSISTANT_LOCAL_STATE = 'UPDATE_ASSISTANT_LOCAL_STATE'
export const SEARCH_ASSISTANT_FILINGS_BY_USER_SUCCESS =
  'SEARCH_ASSISTANT_FILINGS_BY_USER_SUCCESS'
export const SEARCH_ASSISTANT_FILINGS_BY_USER_ERROR =
  'SEARCH_ASSISTANT_FILINGS_BY_USER_ERROR'
export const SEARCH_ASSISTANT_FIREBASE_DOCUMENT_STATUS_SUCCESS =
  '@@SEARCH_ASSISTANT/FIREBASE_DOCUMENT_STATUS_SUCCESS'
export const SEARCH_ASSISTANT_FIREBASE_DOCUMENT_STATUS_ERROR =
  '@@SEARCH_ASSISTANT/FIREBASE_DOCUMENT_STATUS_ERROR'
export const GET_BLOB_FILE_SUCCESS = 'GET_BLOB_FILE_SUCCESSS'
export const CLEAR_BLOB_FILE_SUCCESS = 'CLEAR_BLOB_FILE_SUCCESS'
export const CLEAR_MESSAGE_TO_SHOW = 'CLEAR_MESSAGE_TO_SHOW'
export const UPDATE_ASSISTANT_USERS_SUCCESS = 'UPDATE_ASSISTANT_USERS_SUCCESS'
export const CHANGE_FILLING_ORDER_ASSISTANT_BEGIN =
  'CHANGE_FILLING_ORDER_ASSISTANT_BEGIN'
export const CHANGE_FILLING_ORDER_ASSISTANT_ERROR =
  'CHANGE_FILLING_ORDER_ASSISTANT_ERROR'
export const CHANGE_FILLING_ORDER_ASSISTANT_SUCCESS =
  'CHANGE_FILLING_ORDER_ASSISTANT_SUCCESS'
export const SWAP_ACCOUNT_FROM_ASSISTANT_SUCCESS =
  'SWAP_ACCOUNT_FROM_ASSISTANT_SUCCESS'
export const SWAP_ACCOUNT_FROM_ASSISTANT_ERROR =
  'SWAP_ACCOUNT_FROM_ASSISTANT_ERROR'
export const CHANGE_ORDER_STATUS_BEGIN = 'CHANGE_ORDER_STATUS_BEGIN'
export const CHANGE_ORDER_STATUS_ERROR = 'CHANGE_ORDER_STATUS_ERROR'
export const CHANGE_ORDER_STATUS_SUCCESS = 'CHANGE_ORDER_STATUS_SUCCESS'

export const GET_FILINGS_BY_EMAIL_BEGIN = 'GET_FILINGS_BY_EMAIL_BEGIN'
export const GET_FILINGS_BY_EMAIL_ERROR = 'GET_FILINGS_BY_EMAIL_ERROR'
export const GET_FILINGS_BY_EMAIL_SUCCESS = 'GET_FILINGS_BY_EMAIL_SUCCESS'

export const DIAN_CREDENTIALS_ASSISTANT_SUCCESS =
  'DIAN_CREDENTIALS_ASSISTANT_SUCCESS'
export const DIAN_CREDENTIALS_ASSISTANT_ERROR =
  'DIAN_CREDENTIALS_ASSISTANT_ERROR'
export const ASSISTANT_REFUND_PAYMENT_BEGIN = 'ASSISTANT_REFUND_PAYMENT_BEGIN'
export const ASSISTANT_REFUND_PAYMENT_ERROR = 'ASSISTANT_REFUND_PAYMENT_ERROR'
export const ASSISTANT_REFUND_PAYMENT_SUCCESS =
  'ASSISTANT_REFUND_PAYMENT_SUCCESS'
export const ASSISTANT_REQUEST_REFUND_PAYMENT_ERROR =
  'ASSISTANT_REQUEST_REFUND_PAYMENT_ERROR'
export const ASSISTANT_REQUEST_REFUND_PAYMENT_SUCCESS =
  'ASSISTANT_REQUEST_REFUND_PAYMENT_SUCCESS'

// aranea
export const ARANEA_GET_STATUS_BEGIN = '@@ARANEA/GET_STATUS/BEGIN'
export const ARANEA_GET_STATUS_SUCCESS = '@@ARANEA/GET_STATUS/SUCCESS'
export const ARANEA_GET_STATUS_ERROR = '@@ARANEA/GET_STATUS/ERROR'
export const ARANEA_FLUSH = '@@ARANEA/FLUSH'
export const ARANEA_CLEAN_STATUS = '@@ARANEA/CLEAN/STATUS'
export const ARANEA_CREATE_FILE_PROCESS_BEGIN =
  '@@ARANEA/CREATE_FILE_PROCESS/BEGIN'
export const ARANEA_CREATE_FILE_PROCESS_SUCCESS =
  '@@ARANEA/CREATE_FILE_PROCESS/SUCCESS'
export const ARANEA_CREATE_FILE_PROCESS_ERROR =
  '@@ARANEA/CREATE_FILE_PROCESS/ERROR'
export const ARANEA_SET_DOWNLOADABLE_FILE = '@@ARANEA/SET_DOWNLOADABLE_FILE'
export const ARANEA_POST_DIAN_CREDENTIALS_BEGIN =
  '@@ARANEA/POST_DIAN_CREDENTIALS/BEGIN'
export const ARANEA_POST_DIAN_CREDENTIALS_SUCCESS =
  '@@ARANEA/POST_DIAN_CREDENTIALS/SUCCESS'
export const ARANEA_POST_DIAN_CREDENTIALS_ERROR =
  '@@ARANEA/POST_DIAN_CREDENTIALS/ERROR'
export const ARANEA_SET_FAIL_CONNECTION = '@@ARANEA/SET_FAIL_CONNECTION'
export const ARANEA_GET_ELECTRONIC_SIGNATURE_VALUE_SUCCESS =
  '@@ARANEA/GET_ELECTRONIC_SIGNATURE_VALUE/SUCCESS'
export const ARANEA_GET_ELECTRONIC_SIGNATURE_VALUE_ERROR =
  '@@ARANEA/GET_ELECTRONIC_SIGNATURE_VALUE/ERROR'
export const ARANEA_GET_ELECTRONIC_SIGNATURE_VALUE_BEGIN =
  '@@ARANEA/GET_ELECTRONIC_SIGNATURE_VALUE/BEGIN'
export const ARANEA_CLEAN_SIGNATURE_TRACE = '@@ARANEA/CLEAN/SIGNATURE_TRACE'

// Filings Actions
export const FILING_TABLE_FORMAT = '@@FILING/TABLE/FORMAT'
export const FILING_TABLE_FILTER = '@@FILING/TABLE/FILTER'
export const FILING_TABLE_UPDATE = '@@FILING/TABLE/UPDATE'
