export const LANDING = 'https://www.tributi.com/'

export const ALIANZAS = 'alianzas'
export const SURA_RETAIL = 'suraRetailApp'
export const APP = 'app'
export const CARDIF = 'cardifApp'
export const SURA = 'suraApp'
export const DAVIVIENDA = 'daviviendaApp'
export const PORVENIR = 'povenirApp'
export const PROTECCION = 'proteccionApp'
export const DECLARANTES = 'declarantes'
export const BANCO_DE_BOGOTA = 'bancodebogotaApp'
export const BANCOLOMBIA = 'bancolombiaApp'
export const ONTOP = 'ontopApp'
