runtime: python310
service: taxplanning
instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2

default_expiration: '0d 0h'

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301

  - url: /(.*)/(js|css)/main\.(.*)$
    static_files: build/static/\2/main.\3
    upload: build/(.*)main\.(.*)$

  - url: /(.*)/media/(.*)$
    static_files: build/static/media/\2
    upload: build/(.*)/media/(.*)$

  - url: /images/(.*)
    static_files: build/images/\1
    upload: build/images/(.*)
    secure: always
    redirect_http_response_code: 301

  - url: /(.*\.(ico|js|json))$
    static_files: build/\1
    upload: build/.*\.(ico|js|json)$

  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301
