const formInitialState = {
  loading: false,
  error: null,
  errorUpdate: null,
  userInfo: null,
  plans: [],
  country: [],
  updateUser: false,
  fillingStatus: '',
  updatedFilingsByEmail: null,
  fillingsByEmail: [],
  filingActiveStatusError: null,
  assistantUsers: [],
  assistantPersons: [],
  assistantFilingsByPerson: [],
  assistantDocumentsByFiling: [],
  assistantEnginesByFiling: [],
  assistantPaymentsByFiling: [],
  assistantUserSaved: { error: false },
  assistantPersonSaved: { error: false },
  assistantFilingsByUser: [],
  assistantLocalState: {
    location: '',
    showUsers: false,
    showPersons: false,
    showFilings: false,
    showDocuments: false,
    showEngines: false,
    showPayments: false,
    currentUser: {},
    currentPerson: {},
    emailOrId: {},
    currentFiling: {},
    currentLocation: {},
    showEditUser: false,
    showEditPerson: false,
    searching: false,
    showingFilings: false,
    assistantUsers: [],
    filingsByEmail: [],
  },
}

export default formInitialState
