const onboardingInitialState = {
  loading: false,
  group: [],
  sections: {},
  questionsbyGroup: [],
  groupQuestions: [],
  summaryData: [],
  error: null,
  summaryToOnboarding: false,
  currentGroupFromSummary: null,
  currentBoxFromSummary: null,
  hasMigratedAnswers: false,
  answersRender: [],
  instanceStatus: null,
  answerOnboardingGroup: [],
  numChildren: null,
  questionsbyCodeSummary: [],
  removeCertificateState: false,
  questionsRender: [],
  answersInstance: [],
  waitingCursor: false,
  progress: 0,
  DIANFiles: null,
  answeredQuestions: [],
  answeredQuestionsUpdatedAt: 0,
  loadingNitRUTUpdate: false,
  certificatesUpdates: {},
  filingValidToMigrate: false,
  wasMigrated: null,
  migrationError: false,
  partialOnboardingData: [],
}

export default onboardingInitialState
