export const MAIN = '/'
export const LOG_IN = '/login'
export const AUTH_CALLBACK = '/auth-callback'
export const REGISTER = '/register/:accounttype'
export const FORGOT_PASSWORDS = '/forgotpassword'
export const RECOVER_PASSWORD = '/recoverpassword/:id/:id2'

export const ACCOUNTANT_FILLINGS = '/filings'
export const ONBOARDING = '/filings/:fillingId/onboarding'
export const ASSISTANT_PAYMENT_ROOT = '/filings/:fillingId/assistantpayment'
export const ASSISTANT_PAYMENT =
  '/filings/:fillingId/assistantpayment/:paymentOrderId'
export const FILING_STATUS = '/filingstatus'
export const PAYMENT_PAYU = '/payment'
export const VALIDATE_EMAIL = '/validate-email'

export const TAX_SERVICES = '/services'
export const TAX_SERVICES_LIST = '/services/payment/'
export const TAX_SERVICES_PAYMENT = '/services/payment/:order_id'
export const TAX_SERVICES_ERROR = '/services/error/:order_id'
export const TAX_SERVICES_SUCCESS = '/services/success/:order_id'
export const TAX_SERVICES_PENDING = '/services/pending/:order_id'

export const ASSISTANT = '/assistant'
export const ASSISTANT_LEGACY = '/assistant/legacy'
export const SELECT_PLAN = '/plans'
export const CHANGE_PLAN = '/change-plan'
export const SIGNIN = '/signin'
export const ACCOUNT = '/account'
export const VERIFY_ACCOUNTANT = '/account/verify'
export const COMING_SOON = '/comingsoon'
export const SURA_INFO = '/surainfo'
export const SUMMARY = '/filings/:fillingId/summary'
export const ONBOARDING_STANDALONE = '/onboarding/standalone'
export const ONBOARDING_TYPE = '/filings/:fillingId/:type/onboarding'
export const QUESTIONS =
  '/filings/:fillingId/questions(/edit)?/:pathid/:instanceid'
export const CREATE_FILLING = '/filling/:type'
export const ASSISTED_PLAN = '/assisted-plan'
export const DOCUMENT_LIST = '/document-list'
export const PERSONALIZED_PLAN = '/personalized-plan'
export const GENERATE_PDF = '/generate-pdf/:type'
export const DASHBOARD = '/filings/:fillingId/dashboard'
export const PAYMENT = '/filings/:fillingId/payment'
export const ERROR_404 = '/notfound'
export const LANDING_TRIBUTI = 'https://www.tributi.com/'
export const MAINTENANCE = '/maintenance'
