const paymentIntialState = {
  success: null,
  error: '',
  payment_order: null,
  orderInfo: null,
  order_id: null,
  paymentOrderCanceled: null,
  compute_taxes: null,
  computedTaxesError: false,
  statusTaxEngine: null,
  statusPayment: null,
  tax_engine: null,
  amount: '',
  filling_price: '',
  tax_refund_due: '',
  codeApproved: '',
  codeAmmount: '',
  referralCount: 0,
  referralUsers: [],
  fillingState: [],
  loading: true,
  couponloading: false,
  isDeclarationReady: true,
  plans: [],
  plansError: null,
  couponLoading: false,
  coupon: null,
  couponError: null,
  documentsLoading: false,
  documents: null,
  referralBalance: 0,
  infoEventCalendly: {},
  couponModalShowed: false,
}

export default paymentIntialState
