export const INITIAL_STATE = {
  tableLoading: false,
  persons: [],
  normalized: [],
  filtered: [],
}

export const ACTIONS_TYPES = {
  SET_PERSONS: '@@FILINGS/SET_PERSONS',
  REMOVE_PERSON: '@@FILINGS/REMOVE_PERSON',
  EXCLUDE_OWN_PERSON: '@@FILINGS/EXCLUDE_OWN_PERSON',
  MOCK_FILINGS: '@@FILINGS/MOCK_FILINGS',
  MOCK_DUE_DATES: '@@FILINGS/MOCK_DUE_DATES',
  UPDATE_TABLE: '@@FILINGS/UPDATE_TABLE',
  FORMAT_TABLE: '@@FILINGS/FORMAT_TABLE',
  FILTER_TABLE: '@@FILINGS/FILTER_TABLE',
}
