import shareConstants from '.'

export default {
  ...shareConstants,
  INDIVIDUAL: 'Individual',
  INSTITUTIONAL: 'Institucional',
  RULE_NO_ACTIONS: '01/01/2017',
  RULE_ACTIONS: '01/01/2015',
  YEAR_END_RATE: '12/31/2018',
  LAST_YEAR_END_RATE: '12/31/2017',
  AVERAGE_FISCAL_YEAR_RATE: 2956.43,
  PERCENT_FISCAL_ADJUSTMENT: 4.07,
  START_YEAR: '12/31/2017',
  END_OF_YEAR: '12/31/2018',
  DEPENDENT: 'Dependiente',
  VOLUNTEER: 'Voluntario',
  FEC_BANCOLOMBIA: 'FEC - Bancolombia',
  FEPEP: 'FEPEP',
  FONDO_SURA: 'FondoSURA',
  SOMOSIG: 'SOMOSIG',
  PRESENT: 'Presente',
  FONDEARGOS: 'FONDEARGOS',
  FOMUNE: 'FOMUNE',
  DUNNO: 'No estoy seguro',
  UVT_2019: 34270,
}
