import { connect } from 'react-redux'
import {
  getAssistantFilling,
  editPersonAsAssistant,
  updateStatusFilling,
  changeFilingActiveStatus,
  getAsistantUsers,
  getAssistantPersons,
  getAssistantFilingsByPerson,
  getAssistantDocumentsByFiling,
  getAssistantEnginesByFiling,
  getAssistantPaymentsByFiling,
  saveAssistantUser,
  saveAssistantPerson,
  setAssistantLocalState,
  getAssistantFilingsByUser,
  getFirebaseDocumentStatus,
  changeFilingOrderAssistant,
  swapAccountFromAssistant,
  changeOrderStatus,
  getAssistantFillingByEmail,
  getAssistantDianCredentials,
  assistantRefundPayment,
  getAssistantRequestRefundPayment,
  toggleVideocallException,
} from '../../redux/form/actions'
import { getFillingState, clearEngineStatus } from '../../redux/payment/actions'
import { cancelFileUpload } from '../../redux/onboarding/actions'
import { changeUserPassword } from '../../redux/auth/actions'
import AssistantV2 from './content'

const mapStateToProps = ({
  paymentReducer,
  registerReducer,
  onboardingReducer,
  auth,
}) => ({
  documents: paymentReducer.documents,
  documentsError: paymentReducer.documentsError,
  error: registerReducer.error,
  filingActiveStatusError: registerReducer.filingActiveStatusError,
  filingsByEmail: registerReducer.fillingsByEmail,
  updatedFilingsByEmail: registerReducer.updatedFilingsByEmail,
  assistantUsers: registerReducer.assistantUsers,
  location: registerReducer.location,
  assistantPersons: registerReducer.assistantPersons,
  assistantFilingsByPerson: registerReducer.assistantFilingsByPerson,
  assistantDocumentsByFiling: registerReducer.assistantDocumentsByFiling,
  assistantEnginesByFiling: registerReducer.assistantEnginesByFiling,
  assistantPaymentsByFiling: registerReducer.assistantPaymentsByFiling,
  assistantUserSaved: registerReducer.assistantUserSaved,
  assistantPersonSaved: registerReducer.assistantPersonSaved,
  fillingState: paymentReducer.fillingState,
  assistantLocalState: registerReducer.assistantLocalState,
  assistantFilingsByUser: registerReducer.assistantFilingsByUser,
  cancelFileUploadStatus: onboardingReducer.cancelFileUploadStatus,
  changePasswordSuccessed: auth.changePasswordSuccessed,
  changePasswordLoading: auth.changePasswordLoading,
  assistantDianCredentials: registerReducer.assistantDianCredentials,
  assistantRequestRefundPayments:
    registerReducer.assistantRequestRefundPayments,
})

const mapDispatchToProps = {
  getAssistantFilling,
  updateStatusFilling,
  clearEngineStatus,
  editPersonAsAssistant,
  changeFilingActiveStatus,
  getAsistantUsers,
  getAssistantPersons,
  getAssistantFilingsByPerson,
  getAssistantDocumentsByFiling,
  getAssistantEnginesByFiling,
  getAssistantPaymentsByFiling,
  saveAssistantUser,
  saveAssistantPerson,
  getFillingState,
  setAssistantLocalState,
  getAssistantFilingsByUser,
  cancelFileUpload,
  getFirebaseDocumentStatus,
  changeUserPassword,
  changeFilingOrderAssistant,
  swapAccountFromAssistant,
  changeOrderStatus,
  getAssistantFillingByEmail,
  getAssistantDianCredentials,
  assistantRefundPayment,
  getAssistantRequestRefundPayment,
  toggleVideocallException,
}

export default connect(mapStateToProps, mapDispatchToProps)(AssistantV2)
