name: Setup and build

on: [push]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  task:
    needs: [setup]
    strategy:
      matrix:
        app: ${{fromJson(needs.setup.outputs.apps-matrix)}}
    uses: ./.github/workflows/test.yml
    with:
      app: ${{ matrix.app }}
