name: Setup and build

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      apps-matrix: ${{ steps.apps-matrix.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        env:
          COMMITS: ${{ toJSON(github.event.commits) }}
        id: apps-matrix
        with:
          script: |
            const commits = JSON.parse(process.env.COMMITS)
            const apps = []
            for (const commit of commits) {
              if(commit.message.includes('[app:all]')) {
                apps.push('a','c')
                break
              }
              if(commit.message.includes('[app:a]')) apps.push('a')
              if(commit.message.includes('[app:c]')) apps.push('c')
              if(apps.length === 2) break
            }
            return apps

  task:
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      matrix:
        app: ${{fromJson(needs.setup.outputs.apps-matrix)}}
    steps:
      - name: Build app ${{ matrix.app }}
        run: |
          echo "${{ matrix.app }}"
