name: Setup and build

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      apps_matrix: ${{ steps.apps_matrix.outputs.apps }}
    steps:
      - name: commits
        run: echo ${{ github.event.commits }}
      - name: Get deploy info
        id: apps_matrix
        run: |
          apps=()
          for i in ${{ github.event.commits }} 
          do
            message=$i.message
            echo $message
            app=$(echo $message | grep -o '\[.*\]' | sed 's/^.//;s/.$//')
            echo $app
            if [[ $app == *"all"* ]]; then
              apps=("custom","account")
              break
            fi
            if [[ $app == *"custom"* ]]; then
              apps+=("custom")
            fi
            if [[ $app == *"account"* ]]; then
              apps+=("account")
            fi
            if [ "${#apps[@]}"==2 ]; then
              break
            fi
          done
          echo $apps
          echo $apps >> $GITHUB_OUTPUT

  task:
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.apps_matrix)}}
    steps:
      - name: Matrix value
        run: |
          echo "${{ matrix.value }}"
