name: Setup and build

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      apps-matrix: ${{ steps.apps-matrix.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        env:
          COMMITS: ${{ toJSON(github.event.commits) }}
        id: apps-matrix
        with:
          script: |
            const commits = JSON.parse(process.env.COMMITS)
            const apps = []
            const ALL = 'app:all'
            const APP_C = 'app:c'
            const APP_A = 'app:a'
            for (const commit of commits) {
              const app = commit.message?.match(/\[.*\]/)?.at(0)?.replace(/\s/g,'')?.toLowerCase()              
              if(app.includes(ALL)) {
                apps.push('a','c')
                break
              }
              if(app.includes(APP_A) && !apps.includes('a')) apps.push('a')
              if(app.includes(APP_C) && !apps.includes('c')) apps.push('c')
              if(apps.length === 2) break
            }
            if(!apps.length) apps.push('empty')
            return apps

  task:
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      matrix:
        app: ${{fromJson(needs.setup.outputs.apps-matrix)}}
    steps:
      - name: Build app ${{ matrix.app }}
        if: matrix.app != 'empty'
        run: |
          echo "${{ matrix.app }}"
