name: tests

on:
  workflow_call:
    inputs:
      exclude:
        description: app to exclude
        type: string
    outputs:
      apps-matrix:
        value: ${{ jobs.setup.outputs.apps-matrix }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      apps-matrix: ${{ steps.apps-matrix.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        env:
          COMMITS: ${{ toJSON(github.event.commits) }}
          EXCLUDE: ${{ inputs.exclude }}
        id: apps-matrix
        with:
          script: |
            const commits = JSON.parse(process.env.COMMITS)
            const exclude = process.env.EXCLUDE
            const apps = new Set()
            const ALL = 'app:all'
            const APP_C = 'app:c'
            const APP_A = 'app:a'
            const APP_T = 'app:t'
            for (const commit of commits) {
              const app = commit.message?.match(/\[.*\]/)?.at(0)?.replace(/\s/g,'')?.toLowerCase() || ''
              if(app.includes(ALL)) {
                apps.add('a').add('c').add('t')
                break
              }
              if(app.includes(APP_A)) apps.add('a')
              if(app.includes(APP_C)) apps.add('c')
              if(app.includes(APP_T)) apps.add('t')
              if(apps.size === 3) break
            }
            if(exclude) {
              apps.delete(exclude)
            }
            if(!apps.size) return false
            console.log(apps)
            return [...apps]
