name: tests

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    if: inputs.app != 'empty'
    steps:
      - name: get environment service
        run: |
          APP=${{ inputs.app }}
          if [ $APP == 'c' ]; then
            echo "service=f" >> $GITHUB_ENV
          elif [ $APP == 'a' ]; then
            echo "service=a" >> $GITHUB_ENV
          fi

      - name: name tests ${{ inputs.app }}
        run: echo ${{ env.service }}
