name: tests

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: name tests ${{ inputs.app }}
        run: echo ${{ inputs.app }}
